/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.HomeController;
import view.customClasses.RoundedButton;
import java.awt.*;
import javax.swing.*;
import model.User;
import view.customClasses.RoundedButton.*;
import view.customClasses.RoundedPanel;

/**
 *
 * @author Pedro Schneider, Gabriel Santana Dias
 */
public class HomeWindow extends javax.swing.JFrame {
    
    Toolkit toolkit = Toolkit.getDefaultToolkit();
    private final Dimension screenSize = toolkit.getScreenSize();
    private final int width = screenSize.width;
    private final int height = screenSize.height;
    private User user;
    
    /**
     * Creates new form HomeWindow
     */
    public HomeWindow(User user) {
        initComponents();
        c =  new HomeController(this, user);
        this.user = user;
        
        this.setSize(width, height);
        
        // changes window icon
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/view/logos_imgs/logoSpotifei.png")).getImage());
        
        // center the window

        int x = (screenSize.width - width) / 2;
        int y = (screenSize.height - height) / 2;
        
        this.setLocation(new Point(x,y));
        c.setUserNameOnWindow();
        c.setLikesAndDislikes();
    }
    
    public JButton getBtt_profile() {
        return btt_profile;
    }

    public void setBtt_profile(JButton btt_profile) {
        this.btt_profile = btt_profile;
    }

    public JLabel getLbl_welcome() {
        return lbl_welcome;
    }

    public void setLbl_welcome(JLabel lbl_welcome) {
        this.lbl_welcome = lbl_welcome;
    }

    public JList<String> getListDislikes() {
        return listDislikes;
    }

    public void setListDislikes(JList<String> listDislikes) {
        this.listDislikes = listDislikes;
    }

    public JList<String> getListLikes() {
        return listLikes;
    }

    public void setListLikes(JList<String> listLikes) {
        this.listLikes = listLikes;
    }

    public JLabel getNum_dislikes() {
        return num_dislikes;
    }

    public void setNum_dislikes(JLabel num_dislikes) {
        this.num_dislikes = num_dislikes;
    }

    public JLabel getNum_likes() {
        return num_likes;
    }

    public void setNum_likes(JLabel num_likes) {
        this.num_likes = num_likes;
    }
    
    
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home_pnl_all = new javax.swing.JPanel();
        home_pnl_leftSide = new javax.swing.JPanel();
        home_pnl_titleLogo = new javax.swing.JPanel();
        icon_logo = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        home_pnl_options = new javax.swing.JPanel();
        home_pnl_homeOpt = new javax.swing.JPanel();
        icon_home = new javax.swing.JLabel();
        lbl_home = new javax.swing.JLabel();
        home_pnl_searchOpt = new javax.swing.JPanel();
        icon_search = new javax.swing.JLabel();
        lbl_search = new javax.swing.JLabel();
        home_pnl_playlistOpt = new javax.swing.JPanel();
        icon_playlist = new javax.swing.JLabel();
        lbl_playlist = new javax.swing.JLabel();
        home_pnl_topSide = new javax.swing.JPanel();
        home_pnl_botSide = new javax.swing.JPanel();
        home_pnl_inside = new javax.swing.JPanel();
        btt_profile = new RoundedButton("user_name");
        home_pnl_welcome = new javax.swing.JPanel();
        spacing1 = new javax.swing.JPanel();
        lbl_welcome = new javax.swing.JLabel();
        icon_wave = new javax.swing.JLabel();
        spacing2 = new javax.swing.JPanel();
        home_pnl_topMusics = new RoundedPanel();
        music1 = new RoundedPanel();
        title1 = new javax.swing.JLabel();
        artist1 = new javax.swing.JLabel();
        photo1 = new javax.swing.JPanel();
        music2 = new RoundedPanel();
        title2 = new javax.swing.JLabel();
        artist2 = new javax.swing.JLabel();
        photo2 = new javax.swing.JPanel();
        music3 = new RoundedPanel();
        title3 = new javax.swing.JLabel();
        artist3 = new javax.swing.JLabel();
        photo3 = new javax.swing.JPanel();
        music4 = new RoundedPanel();
        title4 = new javax.swing.JLabel();
        artist4 = new javax.swing.JLabel();
        photo4 = new javax.swing.JPanel();
        music5 = new RoundedPanel();
        title5 = new javax.swing.JLabel();
        artist5 = new javax.swing.JLabel();
        photo5 = new javax.swing.JPanel();
        home_pnl_likes = new RoundedPanel();
        likes = new RoundedPanel();
        num_likes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listLikes = new javax.swing.JList<>();
        pad5 = new javax.swing.JPanel();
        dislikes = new RoundedPanel();
        num_dislikes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listDislikes = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spotifei");
        setResizable(false);

        home_pnl_all.setBackground(new java.awt.Color(28, 28, 28));
        home_pnl_all.setPreferredSize(new java.awt.Dimension(1024, 1024));

        home_pnl_leftSide.setBackground(new java.awt.Color(28, 28, 28));

        home_pnl_titleLogo.setBackground(new java.awt.Color(28, 28, 28));

        icon_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logos_imgs/logoSpotifei.png"))); // NOI18N
        icon_logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbl_title.setFont(new Font("Gotham Black", Font.PLAIN, 24));
        lbl_title.setForeground(new java.awt.Color(30, 215, 96));
        lbl_title.setText("Spotifei");

        javax.swing.GroupLayout home_pnl_titleLogoLayout = new javax.swing.GroupLayout(home_pnl_titleLogo);
        home_pnl_titleLogo.setLayout(home_pnl_titleLogoLayout);
        home_pnl_titleLogoLayout.setHorizontalGroup(
            home_pnl_titleLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_pnl_titleLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_title)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        home_pnl_titleLogoLayout.setVerticalGroup(
            home_pnl_titleLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_pnl_titleLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(home_pnl_titleLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon_logo)
                    .addGroup(home_pnl_titleLogoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbl_title)))
                .addContainerGap())
        );

        home_pnl_options.setBackground(new java.awt.Color(28, 28, 28));
        home_pnl_options.setPreferredSize(new java.awt.Dimension(0, 348));
        home_pnl_options.setLayout(new javax.swing.BoxLayout(home_pnl_options, javax.swing.BoxLayout.Y_AXIS));

        home_pnl_homeOpt.setBackground(new java.awt.Color(28, 28, 28));
        home_pnl_homeOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_pnl_homeOpt.setPreferredSize(new java.awt.Dimension(65, 58));
        home_pnl_homeOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_pnl_homeOptMouseClicked(evt);
            }
        });

        icon_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logos_imgs/homeIcon.png"))); // NOI18N
        home_pnl_homeOpt.add(icon_home);

        lbl_home.setFont(new Font("Gotham Black", Font.PLAIN, 16));
        lbl_home.setForeground(new java.awt.Color(168, 170, 170));
        lbl_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_home.setText("Home");
        home_pnl_homeOpt.add(lbl_home);

        home_pnl_options.add(home_pnl_homeOpt);

        home_pnl_searchOpt.setBackground(new java.awt.Color(28, 28, 28));
        home_pnl_searchOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_pnl_searchOpt.setPreferredSize(new java.awt.Dimension(65, 58));
        home_pnl_searchOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_pnl_searchOptMouseClicked(evt);
            }
        });

        icon_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logos_imgs/searchIcon.png"))); // NOI18N
        home_pnl_searchOpt.add(icon_search);

        lbl_search.setFont(new Font("Gotham Black", Font.PLAIN, 16));
        lbl_search.setForeground(new java.awt.Color(168, 170, 170));
        lbl_search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_search.setText("Buscar");
        home_pnl_searchOpt.add(lbl_search);

        home_pnl_options.add(home_pnl_searchOpt);

        home_pnl_playlistOpt.setBackground(new java.awt.Color(28, 28, 28));
        home_pnl_playlistOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_pnl_playlistOpt.setPreferredSize(new java.awt.Dimension(65, 58));
        home_pnl_playlistOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_pnl_playlistOptMouseClicked(evt);
            }
        });

        icon_playlist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logos_imgs/playlistIcon.png"))); // NOI18N
        home_pnl_playlistOpt.add(icon_playlist);

        lbl_playlist.setFont(new Font("Gotham Black", Font.PLAIN, 16));
        lbl_playlist.setForeground(new java.awt.Color(168, 170, 170));
        lbl_playlist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_playlist.setText("Playlists");
        home_pnl_playlistOpt.add(lbl_playlist);

        home_pnl_options.add(home_pnl_playlistOpt);

        javax.swing.GroupLayout home_pnl_leftSideLayout = new javax.swing.GroupLayout(home_pnl_leftSide);
        home_pnl_leftSide.setLayout(home_pnl_leftSideLayout);
        home_pnl_leftSideLayout.setHorizontalGroup(
            home_pnl_leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_pnl_leftSideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(home_pnl_leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home_pnl_options, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(home_pnl_titleLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        home_pnl_leftSideLayout.setVerticalGroup(
            home_pnl_leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_pnl_leftSideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(home_pnl_titleLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(home_pnl_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(376, Short.MAX_VALUE))
        );

        home_pnl_topSide.setBackground(new java.awt.Color(28, 28, 28));

        javax.swing.GroupLayout home_pnl_topSideLayout = new javax.swing.GroupLayout(home_pnl_topSide);
        home_pnl_topSide.setLayout(home_pnl_topSideLayout);
        home_pnl_topSideLayout.setHorizontalGroup(
            home_pnl_topSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        home_pnl_topSideLayout.setVerticalGroup(
            home_pnl_topSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        home_pnl_botSide.setBackground(new java.awt.Color(28, 28, 28));

        javax.swing.GroupLayout home_pnl_botSideLayout = new javax.swing.GroupLayout(home_pnl_botSide);
        home_pnl_botSide.setLayout(home_pnl_botSideLayout);
        home_pnl_botSideLayout.setHorizontalGroup(
            home_pnl_botSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        home_pnl_botSideLayout.setVerticalGroup(
            home_pnl_botSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        home_pnl_inside.setBackground(new java.awt.Color(18, 18, 18));

        ((RoundedButton) btt_profile).setTextAlignment(TextAlign.LEFT);
        btt_profile.setBackground(new java.awt.Color(185, 192, 198));
        btt_profile.setFont(new java.awt.Font("Gotham", Font.PLAIN, 12));
        btt_profile.setForeground(new java.awt.Color(28, 28, 28));
        btt_profile.setText("user_name");
        btt_profile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 28, 28), 1, true));
        btt_profile.setBorderPainted(false);
        btt_profile.setPreferredSize(new Dimension(200,30));
        btt_profile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btt_profile.setPreferredSize(new java.awt.Dimension(48, 20));
        ((RoundedButton) btt_profile).setCornerRadiusVertical(80);
        ((RoundedButton) btt_profile).setCornerRadiusHorizontal(40);
        btt_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_profileActionPerformed(evt);
            }
        });

        home_pnl_welcome.setBackground(new java.awt.Color(18, 18, 18));
        home_pnl_welcome.setLayout(new javax.swing.BoxLayout(home_pnl_welcome, javax.swing.BoxLayout.LINE_AXIS));

        spacing1.setBackground(new java.awt.Color(18, 18, 18));
        spacing1.setPreferredSize(new java.awt.Dimension(200, 100));

        javax.swing.GroupLayout spacing1Layout = new javax.swing.GroupLayout(spacing1);
        spacing1.setLayout(spacing1Layout);
        spacing1Layout.setHorizontalGroup(
            spacing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );
        spacing1Layout.setVerticalGroup(
            spacing1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        home_pnl_welcome.add(spacing1);

        lbl_welcome.setFont(new java.awt.Font("Gotham Black", Font.PLAIN, 18));
        lbl_welcome.setForeground(new java.awt.Color(168, 170, 170));
        lbl_welcome.setText("Bem-vindo(a), user_name!");
        lbl_welcome.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 15));
        home_pnl_welcome.add(lbl_welcome);

        icon_wave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logos_imgs/waveEmoji.png"))); // NOI18N
        home_pnl_welcome.add(icon_wave);

        spacing2.setBackground(new java.awt.Color(18, 18, 18));
        spacing2.setPreferredSize(new java.awt.Dimension(200, 100));

        javax.swing.GroupLayout spacing2Layout = new javax.swing.GroupLayout(spacing2);
        spacing2.setLayout(spacing2Layout);
        spacing2Layout.setHorizontalGroup(
            spacing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );
        spacing2Layout.setVerticalGroup(
            spacing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        home_pnl_welcome.add(spacing2);

        ((RoundedPanel) home_pnl_topMusics).setHover(0);
        home_pnl_topMusics.setBackground(new java.awt.Color(54, 54, 54));
        home_pnl_topMusics.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        home_pnl_topMusics.setMaximumSize(new java.awt.Dimension(847, 354));
        home_pnl_topMusics.setMinimumSize(new java.awt.Dimension(847, 354));
        home_pnl_topMusics.setPreferredSize(new java.awt.Dimension(847, 354));
        java.awt.GridBagLayout home_pnl_topMusicsLayout = new java.awt.GridBagLayout();
        home_pnl_topMusicsLayout.columnWidths = new int[] {20, 20, 20};
        home_pnl_topMusicsLayout.columnWeights = new double[] {5.0, 5.0, 5.0, 5.0, 5.0};
        home_pnl_topMusics.setLayout(home_pnl_topMusicsLayout);

        ((RoundedPanel) music1).setNormalColor(new Color(18,18,18));
        ((RoundedPanel) music1).setHoverColor(new Color(36,36,36));
        music1.setBackground(new java.awt.Color(18, 18, 18));
        music1.setMaximumSize(new java.awt.Dimension(200, 300));
        music1.setMinimumSize(new java.awt.Dimension(200, 300));
        music1.setPreferredSize(new java.awt.Dimension(200, 300));

        title1.setFont(new Font("Gotham Black", Font.PLAIN, 18));
        title1.setForeground(new java.awt.Color(168, 168, 168));
        title1.setText("title");

        artist1.setFont(new Font("Gotham Black", Font.PLAIN, 18));
        artist1.setForeground(new java.awt.Color(168, 168, 168));
        artist1.setText("artist");

        javax.swing.GroupLayout photo1Layout = new javax.swing.GroupLayout(photo1);
        photo1.setLayout(photo1Layout);
        photo1Layout.setHorizontalGroup(
            photo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        photo1Layout.setVerticalGroup(
            photo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout music1Layout = new javax.swing.GroupLayout(music1);
        music1.setLayout(music1Layout);
        music1Layout.setHorizontalGroup(
            music1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(music1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(music1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(photo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(music1Layout.createSequentialGroup()
                        .addGroup(music1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title1)
                            .addComponent(artist1))
                        .addGap(0, 122, Short.MAX_VALUE)))
                .addContainerGap())
        );
        music1Layout.setVerticalGroup(
            music1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, music1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(title1)
                .addGap(18, 18, 18)
                .addComponent(artist1)
                .addContainerGap())
        );

        home_pnl_topMusics.add(music1, new java.awt.GridBagConstraints());

        ((RoundedPanel) music2).setNormalColor(new Color(18,18,18));
        ((RoundedPanel) music2).setHoverColor(new Color(36,36,36));
        music2.setBackground(new java.awt.Color(18, 18, 18));
        music2.setMaximumSize(new java.awt.Dimension(200, 300));
        music2.setMinimumSize(new java.awt.Dimension(200, 300));
        music2.setPreferredSize(new java.awt.Dimension(200, 300));

        title2.setFont(new Font("Gotham Black", Font.PLAIN, 18));
        title2.setForeground(new java.awt.Color(168, 168, 168));
        title2.setText("title");

        artist2.setFont(new Font("Gotham Black", Font.PLAIN, 18));
        artist2.setForeground(new java.awt.Color(168, 168, 168));
        artist2.setText("artist");

        javax.swing.GroupLayout photo2Layout = new javax.swing.GroupLayout(photo2);
        photo2.setLayout(photo2Layout);
        photo2Layout.setHorizontalGroup(
            photo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        photo2Layout.setVerticalGroup(
            photo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout music2Layout = new javax.swing.GroupLayout(music2);
        music2.setLayout(music2Layout);
        music2Layout.setHorizontalGroup(
            music2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(music2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(music2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(music2Layout.createSequentialGroup()
                        .addGroup(music2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(artist2)
                            .addComponent(title2))
                        .addGap(0, 122, Short.MAX_VALUE))
                    .addComponent(photo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        music2Layout.setVerticalGroup(
            music2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, music2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(title2)
                .addGap(18, 18, 18)
                .addComponent(artist2)
                .addContainerGap())
        );

        home_pnl_topMusics.add(music2, new java.awt.GridBagConstraints());

        ((RoundedPanel) music3).setNormalColor(new Color(18,18,18));
        ((RoundedPanel) music3).setHoverColor(new Color(36,36,36));
        music3.setBackground(new java.awt.Color(18, 18, 18));
        music3.setMaximumSize(new java.awt.Dimension(200, 300));
        music3.setMinimumSize(new java.awt.Dimension(200, 300));
        music3.setPreferredSize(new java.awt.Dimension(200, 300));

        title3.setFont(new Font("Gotham Black", Font.PLAIN, 18));
        title3.setForeground(new java.awt.Color(168, 168, 168));
        title3.setText("title");

        artist3.setFont(new Font("Gotham Black", Font.PLAIN, 18));
        artist3.setForeground(new java.awt.Color(168, 168, 168));
        artist3.setText("artist");

        javax.swing.GroupLayout photo3Layout = new javax.swing.GroupLayout(photo3);
        photo3.setLayout(photo3Layout);
        photo3Layout.setHorizontalGroup(
            photo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        photo3Layout.setVerticalGroup(
            photo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout music3Layout = new javax.swing.GroupLayout(music3);
        music3.setLayout(music3Layout);
        music3Layout.setHorizontalGroup(
            music3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(music3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(music3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(music3Layout.createSequentialGroup()
                        .addGroup(music3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title3)
                            .addComponent(artist3))
                        .addGap(0, 122, Short.MAX_VALUE))
                    .addComponent(photo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        music3Layout.setVerticalGroup(
            music3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, music3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(title3)
                .addGap(18, 18, 18)
                .addComponent(artist3)
                .addContainerGap())
        );

        home_pnl_topMusics.add(music3, new java.awt.GridBagConstraints());

        ((RoundedPanel) music4).setNormalColor(new Color(18,18,18));
        ((RoundedPanel) music4).setHoverColor(new Color(36,36,36));
        music4.setBackground(new java.awt.Color(18, 18, 18));
        music4.setMaximumSize(new java.awt.Dimension(200, 300));
        music4.setMinimumSize(new java.awt.Dimension(200, 300));
        music4.setPreferredSize(new java.awt.Dimension(200, 300));

        title4.setFont(new Font("Gotham Black", Font.PLAIN, 18));
        title4.setForeground(new java.awt.Color(168, 168, 168));
        title4.setText("title");

        artist4.setFont(new Font("Gotham Black", Font.PLAIN, 18));
        artist4.setForeground(new java.awt.Color(168, 168, 168));
        artist4.setText("artist");

        javax.swing.GroupLayout photo4Layout = new javax.swing.GroupLayout(photo4);
        photo4.setLayout(photo4Layout);
        photo4Layout.setHorizontalGroup(
            photo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        photo4Layout.setVerticalGroup(
            photo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout music4Layout = new javax.swing.GroupLayout(music4);
        music4.setLayout(music4Layout);
        music4Layout.setHorizontalGroup(
            music4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(music4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(music4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(music4Layout.createSequentialGroup()
                        .addGroup(music4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title4)
                            .addComponent(artist4))
                        .addGap(0, 122, Short.MAX_VALUE))
                    .addComponent(photo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        music4Layout.setVerticalGroup(
            music4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, music4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(title4)
                .addGap(18, 18, 18)
                .addComponent(artist4)
                .addContainerGap())
        );

        home_pnl_topMusics.add(music4, new java.awt.GridBagConstraints());

        ((RoundedPanel) music5).setNormalColor(new Color(18,18,18));
        ((RoundedPanel) music5).setHoverColor(new Color(36,36,36));
        music5.setBackground(new java.awt.Color(18, 18, 18));
        music5.setMaximumSize(new java.awt.Dimension(200, 300));
        music5.setMinimumSize(new java.awt.Dimension(200, 300));
        music5.setPreferredSize(new java.awt.Dimension(200, 300));

        title5.setFont(new Font("Gotham Black", Font.PLAIN, 18));
        title5.setForeground(new java.awt.Color(168, 168, 168));
        title5.setText("title");

        artist5.setFont(new Font("Gotham Black", Font.PLAIN, 18));
        artist5.setForeground(new java.awt.Color(168, 168, 168));
        artist5.setText("artist");

        javax.swing.GroupLayout photo5Layout = new javax.swing.GroupLayout(photo5);
        photo5.setLayout(photo5Layout);
        photo5Layout.setHorizontalGroup(
            photo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        photo5Layout.setVerticalGroup(
            photo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout music5Layout = new javax.swing.GroupLayout(music5);
        music5.setLayout(music5Layout);
        music5Layout.setHorizontalGroup(
            music5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(music5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(music5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(music5Layout.createSequentialGroup()
                        .addGroup(music5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(title5)
                            .addComponent(artist5))
                        .addGap(0, 122, Short.MAX_VALUE))
                    .addComponent(photo5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        music5Layout.setVerticalGroup(
            music5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, music5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(title5)
                .addGap(18, 18, 18)
                .addComponent(artist5)
                .addContainerGap())
        );

        home_pnl_topMusics.add(music5, new java.awt.GridBagConstraints());

        ((RoundedPanel) home_pnl_likes).setHover(0);
        home_pnl_likes.setBackground(new java.awt.Color(54, 54, 54));
        home_pnl_likes.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        home_pnl_likes.setLayout(new javax.swing.BoxLayout(home_pnl_likes, javax.swing.BoxLayout.X_AXIS));

        ((RoundedPanel) likes).setNormalColor(new Color(18,18,18));
        ((RoundedPanel) likes).setHoverColor(new Color(36,36,36));
        ((RoundedPanel) likes).setHover(0);
        likes.setBackground(new java.awt.Color(18, 18, 18));

        num_likes.setFont(new Font("Gotham Black", Font.PLAIN, 22));
        num_likes.setForeground(new java.awt.Color(168, 168, 168));
        num_likes.setText("likes");

        jScrollPane1.setBackground(new java.awt.Color(60, 63, 65));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(58, 58, 58));

        listLikes.setBackground(new java.awt.Color(18, 18, 18));
        listLikes.setBorder(null);
        listLikes.setFont(new Font("Gotham Light", Font.PLAIN, 14));
        listLikes.setForeground(new java.awt.Color(236, 239, 241));
        listLikes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listLikes.setSelectionBackground(new java.awt.Color(100, 165, 135));
        jScrollPane1.setViewportView(listLikes);

        javax.swing.GroupLayout likesLayout = new javax.swing.GroupLayout(likes);
        likes.setLayout(likesLayout);
        likesLayout.setHorizontalGroup(
            likesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(likesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(likesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addGroup(likesLayout.createSequentialGroup()
                        .addComponent(num_likes)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        likesLayout.setVerticalGroup(
            likesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(likesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(num_likes)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        home_pnl_likes.add(likes);

        pad5.setMaximumSize(new java.awt.Dimension(25, 25));
        pad5.setMinimumSize(new java.awt.Dimension(25, 25));
        pad5.setOpaque(false);
        pad5.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout pad5Layout = new javax.swing.GroupLayout(pad5);
        pad5.setLayout(pad5Layout);
        pad5Layout.setHorizontalGroup(
            pad5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pad5Layout.setVerticalGroup(
            pad5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        home_pnl_likes.add(pad5);

        ((RoundedPanel) dislikes).setNormalColor(new Color(18,18,18));
        ((RoundedPanel) dislikes).setHoverColor(new Color(36,36,36));
        ((RoundedPanel) dislikes).setHover(0);
        dislikes.setBackground(new java.awt.Color(18, 18, 18));

        num_dislikes.setFont(new Font("Gotham Black", Font.PLAIN, 22));
        num_dislikes.setForeground(new java.awt.Color(168, 168, 168));
        num_dislikes.setText("dislikes");

        jScrollPane2.setBackground(new java.awt.Color(60, 63, 65));
        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(58, 58, 58));

        listDislikes.setBackground(new java.awt.Color(18, 18, 18));
        listDislikes.setBorder(null);
        listDislikes.setFont(new Font("Gotham Light", Font.PLAIN, 14));
        listDislikes.setForeground(new java.awt.Color(236, 239, 241));
        listDislikes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listDislikes.setSelectionBackground(new java.awt.Color(100, 165, 135));
        jScrollPane2.setViewportView(listDislikes);

        javax.swing.GroupLayout dislikesLayout = new javax.swing.GroupLayout(dislikes);
        dislikes.setLayout(dislikesLayout);
        dislikesLayout.setHorizontalGroup(
            dislikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dislikesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dislikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                    .addGroup(dislikesLayout.createSequentialGroup()
                        .addComponent(num_dislikes)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dislikesLayout.setVerticalGroup(
            dislikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dislikesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(num_dislikes)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        home_pnl_likes.add(dislikes);

        javax.swing.GroupLayout home_pnl_insideLayout = new javax.swing.GroupLayout(home_pnl_inside);
        home_pnl_inside.setLayout(home_pnl_insideLayout);
        home_pnl_insideLayout.setHorizontalGroup(
            home_pnl_insideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_pnl_insideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(home_pnl_insideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, home_pnl_insideLayout.createSequentialGroup()
                        .addComponent(home_pnl_welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btt_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(home_pnl_likes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(home_pnl_topMusics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        home_pnl_insideLayout.setVerticalGroup(
            home_pnl_insideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_pnl_insideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(home_pnl_insideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(home_pnl_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btt_profile, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(home_pnl_topMusics, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(home_pnl_likes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout home_pnl_allLayout = new javax.swing.GroupLayout(home_pnl_all);
        home_pnl_all.setLayout(home_pnl_allLayout);
        home_pnl_allLayout.setHorizontalGroup(
            home_pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_pnl_botSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(home_pnl_allLayout.createSequentialGroup()
                .addComponent(home_pnl_leftSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(home_pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home_pnl_inside, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(home_pnl_topSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        home_pnl_allLayout.setVerticalGroup(
            home_pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_pnl_allLayout.createSequentialGroup()
                .addGroup(home_pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(home_pnl_allLayout.createSequentialGroup()
                        .addComponent(home_pnl_topSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(home_pnl_inside, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(home_pnl_leftSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(home_pnl_botSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_pnl_all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_pnl_all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btt_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_profileActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btt_profileActionPerformed

    private void home_pnl_homeOptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_pnl_homeOptMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_home_pnl_homeOptMouseClicked

    private void home_pnl_searchOptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_pnl_searchOptMouseClicked
        // TODO add your handling code here:
        SearchWindow sw = new SearchWindow(user);
        sw.setVisible(rootPaneCheckingEnabled);
        this.setVisible(false);
    }//GEN-LAST:event_home_pnl_searchOptMouseClicked

    private void home_pnl_playlistOptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_pnl_playlistOptMouseClicked
        // TODO add your handling code here:
        PlaylistsWindow pw = new PlaylistsWindow(user);
        pw.setVisible(rootPaneCheckingEnabled);
        this.setVisible(false);
    }//GEN-LAST:event_home_pnl_playlistOptMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomeWindow().setVisible(true);
//            }
//        });
//    }
    
    private HomeController c;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel artist1;
    private javax.swing.JLabel artist2;
    private javax.swing.JLabel artist3;
    private javax.swing.JLabel artist4;
    private javax.swing.JLabel artist5;
    private javax.swing.JButton btt_profile;
    private javax.swing.JPanel dislikes;
    private javax.swing.JPanel home_pnl_all;
    private javax.swing.JPanel home_pnl_botSide;
    private javax.swing.JPanel home_pnl_homeOpt;
    private javax.swing.JPanel home_pnl_inside;
    private javax.swing.JPanel home_pnl_leftSide;
    private javax.swing.JPanel home_pnl_likes;
    private javax.swing.JPanel home_pnl_options;
    private javax.swing.JPanel home_pnl_playlistOpt;
    private javax.swing.JPanel home_pnl_searchOpt;
    private javax.swing.JPanel home_pnl_titleLogo;
    private javax.swing.JPanel home_pnl_topMusics;
    private javax.swing.JPanel home_pnl_topSide;
    private javax.swing.JPanel home_pnl_welcome;
    private javax.swing.JLabel icon_home;
    private javax.swing.JLabel icon_logo;
    private javax.swing.JLabel icon_playlist;
    private javax.swing.JLabel icon_search;
    private javax.swing.JLabel icon_wave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_home;
    private javax.swing.JLabel lbl_playlist;
    private javax.swing.JLabel lbl_search;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JPanel likes;
    private javax.swing.JList<String> listDislikes;
    private javax.swing.JList<String> listLikes;
    private javax.swing.JPanel music1;
    private javax.swing.JPanel music2;
    private javax.swing.JPanel music3;
    private javax.swing.JPanel music4;
    private javax.swing.JPanel music5;
    private javax.swing.JLabel num_dislikes;
    private javax.swing.JLabel num_likes;
    private javax.swing.JPanel pad5;
    private javax.swing.JPanel photo1;
    private javax.swing.JPanel photo2;
    private javax.swing.JPanel photo3;
    private javax.swing.JPanel photo4;
    private javax.swing.JPanel photo5;
    private javax.swing.JPanel spacing1;
    private javax.swing.JPanel spacing2;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JLabel title4;
    private javax.swing.JLabel title5;
    // End of variables declaration//GEN-END:variables
}
