/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import view.customClasses.RoundedButton;
import view.customClasses.PlaceholderFields;
import controller.LoginController;
import java.awt.*;
import javax.swing.*;
import view.customClasses.PlaceholderPassword;
import view.customDialogs.CustomJDialog;

/**
 *
 * @author Pedro Schneider, Gabriel Santana Dias
 */
public class LoginWindow extends javax.swing.JFrame {

    Toolkit toolkit = Toolkit.getDefaultToolkit();
    private final Dimension screenSize = toolkit.getScreenSize();
    private final int width = 512;
    private final int height = 448;
    
    /**
     * Creates new form LoginWindow
     */
    public LoginWindow() {
        initComponents();
        c = new LoginController(this);
                
        this.setSize(width, height);
        
        // changes window icon
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/view/assets/images/logoSpotifei.png")).getImage());
        
        // get the screen size and center the window
        int x = (screenSize.width - width) / 2;
        int y = (screenSize.height - height) / 2;
        
        this.setLocation(new Point(x,y));
        this.setMinimumSize(new Dimension(512, 448));
        
        // set maximum size of the window
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                int maxWidth = 1024;
                int maxHeight = 896;

                int width = getWidth();
                int height = getHeight();

                if (width > maxWidth || height > maxHeight) {
                    setSize(Math.min(width, maxWidth), Math.min(height, maxHeight));
                }
            }
        });
                
        // center panel after layout is initialized
        SwingUtilities.invokeLater(() -> {
            centerLoginPanel();
            setupEnterKeyBinding();
            // addResizeListener();
        });
    }
    
    // set enter as key bind for login
    private void setupEnterKeyBinding() {
        InputMap im = btt_login.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap am = btt_login.getActionMap();

        im.put(KeyStroke.getKeyStroke("ENTER"), "login");
        am.put("login", new AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                btt_loginActionPerformed(e);
            }
        });
    }

    private void centerLoginPanel() {
        int panelHeight = login_pnl_all.getHeight();
        int loginPanelHeight = login_pnl_login.getPreferredSize().height;
        int logoHeight = login_pnl_titleLogo.getPreferredSize().height;

        int topMargin = 20;
        int spaceAfterLogo = 30;

        int remainingHeight = panelHeight - (logoHeight + topMargin + spaceAfterLogo);
        int y = logoHeight + topMargin + spaceAfterLogo + (remainingHeight - loginPanelHeight) / 2;

        int panelWidth = login_pnl_all.getWidth();
        int loginPanelWidth = login_pnl_login.getPreferredSize().width;
        int x = (panelWidth - loginPanelWidth) / 2;

        // important: set layout to null for manual placement
        login_pnl_all.setLayout(null);
        login_pnl_titleLogo.setBounds((panelWidth - login_pnl_titleLogo.getPreferredSize().width) / 2, topMargin,
                                      login_pnl_titleLogo.getPreferredSize().width,
                                      login_pnl_titleLogo.getPreferredSize().height);

        login_pnl_login.setBounds(x, y - 20, loginPanelWidth, loginPanelHeight);

        login_pnl_all.revalidate();
        login_pnl_all.repaint();
    }

    // TODO: use this resize listener for home reponsiveness
//    private void addResizeListener() {
//        login_pnl_all.addComponentListener(new java.awt.event.ComponentAdapter() {
//            @Override
//            public void componentResized(java.awt.event.ComponentEvent evt) {
//                centerLoginPanel();
//            }
//        });
//    }
    
    public JTextField getTxt_login() {
        return txt_login;
    }

    public void setTxt_login(JTextField txt_login) {
        this.txt_login = txt_login;
    }

    public JPasswordField getTxt_password() {
        return txt_password;
    }

    public void setTxt_password(JPasswordField txt_password) {
        this.txt_password = txt_password;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_pnl_all = new javax.swing.JPanel();
        login_pnl_titleLogo = new javax.swing.JPanel();
        icon_logo = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        login_pnl_login = new javax.swing.JPanel();
        txt_login = new PlaceholderFields("Login...", new Insets(0, 15, 0, 0));
        txt_password = new PlaceholderPassword("Senha...", new Insets(0, 15, 0, 0));
        btt_login = new RoundedButton("Entrar") ;
        btt_register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spotifei");
        setBackground(new java.awt.Color(28, 28, 28));
        setResizable(false);

        login_pnl_all.setBackground(new java.awt.Color(28, 28, 28));

        login_pnl_titleLogo.setBackground(new java.awt.Color(28, 28, 28));

        icon_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/images/logoSpotifei.png"))); // NOI18N
        icon_logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbl_title.setFont(new Font("Gotham Black", Font.PLAIN, 24));
        lbl_title.setForeground(new java.awt.Color(30, 215, 96));
        lbl_title.setText("Spotifei");

        javax.swing.GroupLayout login_pnl_titleLogoLayout = new javax.swing.GroupLayout(login_pnl_titleLogo);
        login_pnl_titleLogo.setLayout(login_pnl_titleLogoLayout);
        login_pnl_titleLogoLayout.setHorizontalGroup(
            login_pnl_titleLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_pnl_titleLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_title)
                .addContainerGap())
        );
        login_pnl_titleLogoLayout.setVerticalGroup(
            login_pnl_titleLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_pnl_titleLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(login_pnl_titleLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon_logo)
                    .addGroup(login_pnl_titleLogoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbl_title)))
                .addContainerGap())
        );

        login_pnl_login.setBackground(new java.awt.Color(28, 28, 28));

        txt_login.setBackground(new java.awt.Color(51, 51, 51));
        txt_login.setFont(new java.awt.Font("Gotham Thin", 1, 14));
        txt_login.setForeground(new java.awt.Color(168, 170, 170));
        txt_login.setBorder(null);
        txt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_loginActionPerformed(evt);
            }
        });

        txt_password.setBackground(new java.awt.Color(51, 51, 51));
        txt_password.setFont(new java.awt.Font("Gotham Thin", 1, 14));
        txt_password.setForeground(new java.awt.Color(168, 170, 170));
        txt_password.setBorder(null);

        btt_login.setBackground(new java.awt.Color(185, 192, 198));
        btt_login.setFont(new java.awt.Font("Gotham Black", Font.PLAIN, 18));
        btt_login.setForeground(new java.awt.Color(28, 28, 28));
        btt_login.setText("Entrar");
        btt_login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 28, 28), 1, true));
        btt_login.setBorderPainted(false);
        btt_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btt_login.setPreferredSize(new java.awt.Dimension(170, 50));
        btt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_loginActionPerformed(evt);
            }
        });
        btt_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btt_loginKeyPressed(evt);
            }
        });

        btt_register.setBackground(new java.awt.Color(28, 28, 28));
        btt_register.setFont(new java.awt.Font("Gotham Light", Font.ITALIC, 13));
        btt_register.setForeground(new java.awt.Color(236, 239, 241));
        btt_register.setText("Não possui cadastro? Registre-se agora!");
        btt_register.setBorderPainted(false);
        btt_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btt_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout login_pnl_loginLayout = new javax.swing.GroupLayout(login_pnl_login);
        login_pnl_login.setLayout(login_pnl_loginLayout);
        login_pnl_loginLayout.setHorizontalGroup(
            login_pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_pnl_loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(login_pnl_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(login_pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btt_register, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(txt_password))
                .addContainerGap())
            .addGroup(login_pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(login_pnl_loginLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txt_login, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        login_pnl_loginLayout.setVerticalGroup(
            login_pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_pnl_loginLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btt_register))
            .addGroup(login_pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(login_pnl_loginLayout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(txt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(179, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout login_pnl_allLayout = new javax.swing.GroupLayout(login_pnl_all);
        login_pnl_all.setLayout(login_pnl_allLayout);
        login_pnl_allLayout.setHorizontalGroup(
            login_pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_pnl_allLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(login_pnl_titleLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_pnl_allLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(login_pnl_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        login_pnl_allLayout.setVerticalGroup(
            login_pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_pnl_allLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login_pnl_titleLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(login_pnl_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_pnl_all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_pnl_all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btt_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_registerActionPerformed
        // TODO add your handling code here:
        RegistrationWindow rw = new RegistrationWindow(false);
        rw.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btt_registerActionPerformed

    private void btt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_loginActionPerformed
        // TODO add your handling code here:
        try {
        c.login();
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println();
            System.out.println(e.getMessage());
            CustomJDialog.showCustomDialog("Erro!", "Ocorreu um erro inesperado.");
        }
    }//GEN-LAST:event_btt_loginActionPerformed

    private void txt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_loginActionPerformed
        // TODO add your handling code here:
        btt_loginActionPerformed(null);
    }//GEN-LAST:event_txt_loginActionPerformed

    private void btt_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btt_loginKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btt_loginKeyPressed
   
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginWindow().setVisible(true);
//            }
//        });
//    }
    
    private LoginController c;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_login;
    private javax.swing.JButton btt_register;
    private javax.swing.JLabel icon_logo;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JPanel login_pnl_all;
    private javax.swing.JPanel login_pnl_login;
    private javax.swing.JPanel login_pnl_titleLogo;
    private javax.swing.JTextField txt_login;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
}
