/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.PlaylistsController;
import view.customClasses.RoundedButton;
import java.awt.*;
import javax.swing.*;
import model.User;
import view.customClasses.RoundedButton.*;
import view.customClasses.RoundedPanel;

/**
 *
 * @author Pedro Schneider, Gabriel Santana Dias
 */
public class PlaylistsWindow extends javax.swing.JFrame {
    
    Toolkit toolkit = Toolkit.getDefaultToolkit();
    private final Dimension screenSize = toolkit.getScreenSize();
    private final int width = screenSize.width;
    private final int height = screenSize.height;
    private User user;

    /**
     * Creates new form HomeWindow
     */
    public PlaylistsWindow(User user) {
        initComponents();
        this.user = user;
        c = new PlaylistsController(this, user);
        
        this.setSize(width, height);
        
        // changes window icon
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/view/assets/images/logoSpotifei.png")).getImage());
        
        // center the window

        int x = (screenSize.width - width) / 2;
        int y = (screenSize.height - height) / 2;
        
        this.setLocation(new Point(x,y));
    }

    public JList<String> getList_playlists() {
        return list_playlists;
    }

    public void setList_playlists(JList<String> list_playlists) {
        this.list_playlists = list_playlists;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playlist_pnl_all = new javax.swing.JPanel();
        playlist_pnl_leftSide = new javax.swing.JPanel();
        home_pnl_titleLogo = new javax.swing.JPanel();
        icon_logo = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        home_pnl_options = new javax.swing.JPanel();
        home_pnl_homeOpt = new javax.swing.JPanel();
        icon_home = new javax.swing.JLabel();
        lbl_home = new javax.swing.JLabel();
        home_pnl_searchOpt = new javax.swing.JPanel();
        icon_search = new javax.swing.JLabel();
        lbl_search = new javax.swing.JLabel();
        home_pnl_playlistOpt = new javax.swing.JPanel();
        icon_playlist = new javax.swing.JLabel();
        lbl_playlist = new javax.swing.JLabel();
        playlist_pnl_topSide = new javax.swing.JPanel();
        playlist_pnl_botSide = new javax.swing.JPanel();
        playlist_pnl_inside = new javax.swing.JPanel();
        btt_profile = new RoundedButton("user_name");
        playlist_pnl_welcome = new javax.swing.JPanel();
        icon_playlists = new javax.swing.JLabel();
        lbl_playlists = new javax.swing.JLabel();
        spacing2 = new javax.swing.JPanel();
        playlist_pnl_playlists = new RoundedPanel();
        scroll_playlists = new javax.swing.JScrollPane();
        list_playlists = new javax.swing.JList<>();
        btt_removeMusic = new RoundedButton("Remover música");
        btt_removePlaylist = new RoundedButton("Apagar playlist");
        btt_addPlaylist = new RoundedButton("Adicionar playlist");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spotifei");
        setResizable(false);

        playlist_pnl_all.setBackground(new java.awt.Color(28, 28, 28));

        playlist_pnl_leftSide.setBackground(new java.awt.Color(28, 28, 28));

        home_pnl_titleLogo.setBackground(new java.awt.Color(28, 28, 28));

        icon_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/images/logoSpotifei.png"))); // NOI18N
        icon_logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbl_title.setFont(new Font("Gotham Black", Font.PLAIN, 24));
        lbl_title.setForeground(new java.awt.Color(30, 215, 96));
        lbl_title.setText("Spotifei");

        javax.swing.GroupLayout home_pnl_titleLogoLayout = new javax.swing.GroupLayout(home_pnl_titleLogo);
        home_pnl_titleLogo.setLayout(home_pnl_titleLogoLayout);
        home_pnl_titleLogoLayout.setHorizontalGroup(
            home_pnl_titleLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_pnl_titleLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        home_pnl_titleLogoLayout.setVerticalGroup(
            home_pnl_titleLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_pnl_titleLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(home_pnl_titleLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon_logo)
                    .addGroup(home_pnl_titleLogoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbl_title)))
                .addContainerGap())
        );

        home_pnl_options.setBackground(new java.awt.Color(28, 28, 28));
        home_pnl_options.setPreferredSize(new java.awt.Dimension(0, 348));
        home_pnl_options.setLayout(new javax.swing.BoxLayout(home_pnl_options, javax.swing.BoxLayout.Y_AXIS));

        home_pnl_homeOpt.setBackground(new java.awt.Color(28, 28, 28));
        home_pnl_homeOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_pnl_homeOpt.setPreferredSize(new java.awt.Dimension(65, 58));
        home_pnl_homeOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_pnl_homeOptMouseClicked(evt);
            }
        });

        icon_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/images/homeIcon.png"))); // NOI18N
        home_pnl_homeOpt.add(icon_home);

        lbl_home.setFont(new Font("Gotham Black", Font.PLAIN, 16));
        lbl_home.setForeground(new java.awt.Color(168, 170, 170));
        lbl_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_home.setText("Home");
        home_pnl_homeOpt.add(lbl_home);

        home_pnl_options.add(home_pnl_homeOpt);

        home_pnl_searchOpt.setBackground(new java.awt.Color(28, 28, 28));
        home_pnl_searchOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_pnl_searchOpt.setPreferredSize(new java.awt.Dimension(65, 58));
        home_pnl_searchOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_pnl_searchOptMouseClicked(evt);
            }
        });

        icon_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/images/searchIcon.png"))); // NOI18N
        home_pnl_searchOpt.add(icon_search);

        lbl_search.setFont(new Font("Gotham Black", Font.PLAIN, 16));
        lbl_search.setForeground(new java.awt.Color(168, 170, 170));
        lbl_search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_search.setText("Buscar");
        home_pnl_searchOpt.add(lbl_search);

        home_pnl_options.add(home_pnl_searchOpt);

        home_pnl_playlistOpt.setBackground(new java.awt.Color(28, 28, 28));
        home_pnl_playlistOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_pnl_playlistOpt.setPreferredSize(new java.awt.Dimension(65, 58));
        home_pnl_playlistOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home_pnl_playlistOptMouseEntered(evt);
            }
        });

        icon_playlist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/images/playlistIcon.png"))); // NOI18N
        home_pnl_playlistOpt.add(icon_playlist);

        lbl_playlist.setFont(new Font("Gotham Black", Font.PLAIN, 16));
        lbl_playlist.setForeground(new java.awt.Color(168, 170, 170));
        lbl_playlist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_playlist.setText("Playlists");
        home_pnl_playlistOpt.add(lbl_playlist);

        home_pnl_options.add(home_pnl_playlistOpt);

        javax.swing.GroupLayout playlist_pnl_leftSideLayout = new javax.swing.GroupLayout(playlist_pnl_leftSide);
        playlist_pnl_leftSide.setLayout(playlist_pnl_leftSideLayout);
        playlist_pnl_leftSideLayout.setHorizontalGroup(
            playlist_pnl_leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playlist_pnl_leftSideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playlist_pnl_leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home_pnl_options, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(home_pnl_titleLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        playlist_pnl_leftSideLayout.setVerticalGroup(
            playlist_pnl_leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playlist_pnl_leftSideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(home_pnl_titleLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(home_pnl_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(376, Short.MAX_VALUE))
        );

        playlist_pnl_topSide.setBackground(new java.awt.Color(28, 28, 28));

        javax.swing.GroupLayout playlist_pnl_topSideLayout = new javax.swing.GroupLayout(playlist_pnl_topSide);
        playlist_pnl_topSide.setLayout(playlist_pnl_topSideLayout);
        playlist_pnl_topSideLayout.setHorizontalGroup(
            playlist_pnl_topSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        playlist_pnl_topSideLayout.setVerticalGroup(
            playlist_pnl_topSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        playlist_pnl_botSide.setBackground(new java.awt.Color(28, 28, 28));

        javax.swing.GroupLayout playlist_pnl_botSideLayout = new javax.swing.GroupLayout(playlist_pnl_botSide);
        playlist_pnl_botSide.setLayout(playlist_pnl_botSideLayout);
        playlist_pnl_botSideLayout.setHorizontalGroup(
            playlist_pnl_botSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        playlist_pnl_botSideLayout.setVerticalGroup(
            playlist_pnl_botSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        playlist_pnl_inside.setBackground(new java.awt.Color(18, 18, 18));

        ((RoundedButton) btt_profile).setTextAlignment(TextAlign.LEFT);
        btt_profile.setBackground(new java.awt.Color(185, 192, 198));
        btt_profile.setFont(new java.awt.Font("Gotham", Font.PLAIN, 12));
        btt_profile.setForeground(new java.awt.Color(28, 28, 28));
        btt_profile.setText("user_name");
        btt_profile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 28, 28), 1, true));
        btt_profile.setBorderPainted(false);
        btt_profile.setPreferredSize(new Dimension(200,30));
        btt_profile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ((RoundedButton) btt_profile).setCornerRadiusVertical(80);
        ((RoundedButton) btt_profile).setCornerRadiusHorizontal(40);
        btt_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_profileActionPerformed(evt);
            }
        });

        playlist_pnl_welcome.setBackground(new java.awt.Color(18, 18, 18));
        playlist_pnl_welcome.setLayout(new javax.swing.BoxLayout(playlist_pnl_welcome, javax.swing.BoxLayout.LINE_AXIS));

        icon_playlists.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/assets/images/playlistIcon.png"))); // NOI18N
        playlist_pnl_welcome.add(icon_playlists);

        lbl_playlists.setFont(new java.awt.Font("Gotham Black", Font.PLAIN, 18));
        lbl_playlists.setForeground(new java.awt.Color(168, 170, 170));
        lbl_playlists.setText("Estas são suas playlists!");
        lbl_playlists.setBorder(BorderFactory.createEmptyBorder(0, 15, 0, 0));
        playlist_pnl_welcome.add(lbl_playlists);

        spacing2.setBackground(new java.awt.Color(18, 18, 18));
        spacing2.setPreferredSize(new java.awt.Dimension(200, 100));

        javax.swing.GroupLayout spacing2Layout = new javax.swing.GroupLayout(spacing2);
        spacing2.setLayout(spacing2Layout);
        spacing2Layout.setHorizontalGroup(
            spacing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );
        spacing2Layout.setVerticalGroup(
            spacing2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        playlist_pnl_welcome.add(spacing2);

        ((RoundedPanel) playlist_pnl_playlists).setHover(0);
        playlist_pnl_playlists.setBackground(new java.awt.Color(54, 54, 54));
        playlist_pnl_playlists.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        playlist_pnl_playlists.setLayout(new javax.swing.BoxLayout(playlist_pnl_playlists, javax.swing.BoxLayout.LINE_AXIS));

        scroll_playlists.setBackground(new java.awt.Color(60, 63, 65));
        scroll_playlists.setBorder(null);
        scroll_playlists.setForeground(new java.awt.Color(58, 58, 58));

        list_playlists.setBackground(new java.awt.Color(54, 54, 54));
        list_playlists.setBorder(null);
        list_playlists.setFont(new Font("Gotham Light", Font.PLAIN, 14));
        list_playlists.setForeground(new java.awt.Color(236, 239, 241));
        list_playlists.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "playlists" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list_playlists.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list_playlists.setSelectionBackground(new java.awt.Color(100, 165, 135));
        scroll_playlists.setViewportView(list_playlists);

        playlist_pnl_playlists.add(scroll_playlists);

        btt_removeMusic.setBackground(new java.awt.Color(168, 170, 170));
        btt_removeMusic.setFont(new java.awt.Font("Gotham Black", Font.PLAIN, 12));
        btt_removeMusic.setForeground(new java.awt.Color(28, 28, 28));
        btt_removeMusic.setBorder(null);
        btt_removeMusic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btt_removeMusic.setMaximumSize(new java.awt.Dimension(120, 40));
        btt_removeMusic.setMinimumSize(new java.awt.Dimension(120, 40));
        btt_removeMusic.setPreferredSize(new java.awt.Dimension(120, 40));
        ((RoundedButton) btt_removeMusic).setCornerRadiusVertical(20);
        ((RoundedButton) btt_removeMusic).setCornerRadiusHorizontal(20);

        btt_removePlaylist.setBackground(new java.awt.Color(168, 170, 170));
        btt_removePlaylist.setFont(new java.awt.Font("Gotham Black", Font.PLAIN, 12));
        btt_removePlaylist.setForeground(new java.awt.Color(28, 28, 28));
        btt_removePlaylist.setBorder(null);
        btt_removePlaylist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btt_removePlaylist.setMaximumSize(new java.awt.Dimension(120, 40));
        btt_removePlaylist.setMinimumSize(new java.awt.Dimension(120, 40));
        btt_removePlaylist.setPreferredSize(new java.awt.Dimension(120, 40));
        ((RoundedButton) btt_removePlaylist).setCornerRadiusVertical(20);
        ((RoundedButton) btt_removePlaylist).setCornerRadiusHorizontal(20);

        btt_addPlaylist.setBackground(new java.awt.Color(168, 170, 170));
        btt_addPlaylist.setFont(new java.awt.Font("Gotham Black", Font.PLAIN, 12));
        btt_addPlaylist.setForeground(new java.awt.Color(28, 28, 28));
        btt_addPlaylist.setBorder(null);
        btt_addPlaylist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btt_addPlaylist.setMaximumSize(new java.awt.Dimension(120, 40));
        btt_addPlaylist.setMinimumSize(new java.awt.Dimension(120, 40));
        btt_addPlaylist.setPreferredSize(new java.awt.Dimension(120, 40));
        ((RoundedButton) btt_addPlaylist).setCornerRadiusVertical(20);
        ((RoundedButton) btt_addPlaylist).setCornerRadiusHorizontal(20);

        javax.swing.GroupLayout playlist_pnl_insideLayout = new javax.swing.GroupLayout(playlist_pnl_inside);
        playlist_pnl_inside.setLayout(playlist_pnl_insideLayout);
        playlist_pnl_insideLayout.setHorizontalGroup(
            playlist_pnl_insideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playlist_pnl_insideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playlist_pnl_insideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(playlist_pnl_playlists, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playlist_pnl_welcome, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(playlist_pnl_insideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btt_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(playlist_pnl_insideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btt_removeMusic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addComponent(btt_removePlaylist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btt_addPlaylist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        playlist_pnl_insideLayout.setVerticalGroup(
            playlist_pnl_insideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playlist_pnl_insideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playlist_pnl_insideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(playlist_pnl_welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btt_profile, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(playlist_pnl_insideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playlist_pnl_insideLayout.createSequentialGroup()
                        .addComponent(btt_addPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btt_removePlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btt_removeMusic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(playlist_pnl_playlists, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout playlist_pnl_allLayout = new javax.swing.GroupLayout(playlist_pnl_all);
        playlist_pnl_all.setLayout(playlist_pnl_allLayout);
        playlist_pnl_allLayout.setHorizontalGroup(
            playlist_pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playlist_pnl_botSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(playlist_pnl_allLayout.createSequentialGroup()
                .addComponent(playlist_pnl_leftSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(playlist_pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playlist_pnl_inside, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playlist_pnl_topSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        playlist_pnl_allLayout.setVerticalGroup(
            playlist_pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playlist_pnl_allLayout.createSequentialGroup()
                .addGroup(playlist_pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playlist_pnl_allLayout.createSequentialGroup()
                        .addComponent(playlist_pnl_topSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(playlist_pnl_inside, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(playlist_pnl_leftSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playlist_pnl_botSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playlist_pnl_all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playlist_pnl_all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btt_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_profileActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btt_profileActionPerformed

    private void home_pnl_homeOptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_pnl_homeOptMouseClicked
        // TODO add your handling code here:
        HomeWindow hw = new HomeWindow(user);
        hw.setVisible(rootPaneCheckingEnabled);
        this.setVisible(false);
    }//GEN-LAST:event_home_pnl_homeOptMouseClicked

    private void home_pnl_searchOptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_pnl_searchOptMouseClicked
        // TODO add your handling code here:
        SearchWindow sw = new SearchWindow(user);
        sw.setVisible(rootPaneCheckingEnabled);
        this.setVisible(false);
    }//GEN-LAST:event_home_pnl_searchOptMouseClicked

    private void home_pnl_playlistOptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_pnl_playlistOptMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_home_pnl_playlistOptMouseEntered

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomeWindow().setVisible(true);
//            }
//        });
//    }

    private PlaylistsController c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_addPlaylist;
    private javax.swing.JButton btt_profile;
    private javax.swing.JButton btt_removeMusic;
    private javax.swing.JButton btt_removePlaylist;
    private javax.swing.JPanel home_pnl_homeOpt;
    private javax.swing.JPanel home_pnl_options;
    private javax.swing.JPanel home_pnl_playlistOpt;
    private javax.swing.JPanel home_pnl_searchOpt;
    private javax.swing.JPanel home_pnl_titleLogo;
    private javax.swing.JLabel icon_home;
    private javax.swing.JLabel icon_logo;
    private javax.swing.JLabel icon_playlist;
    private javax.swing.JLabel icon_playlists;
    private javax.swing.JLabel icon_search;
    private javax.swing.JLabel lbl_home;
    private javax.swing.JLabel lbl_playlist;
    private javax.swing.JLabel lbl_playlists;
    private javax.swing.JLabel lbl_search;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JList<String> list_playlists;
    private javax.swing.JPanel playlist_pnl_all;
    private javax.swing.JPanel playlist_pnl_botSide;
    private javax.swing.JPanel playlist_pnl_inside;
    private javax.swing.JPanel playlist_pnl_leftSide;
    private javax.swing.JPanel playlist_pnl_playlists;
    private javax.swing.JPanel playlist_pnl_topSide;
    private javax.swing.JPanel playlist_pnl_welcome;
    private javax.swing.JScrollPane scroll_playlists;
    private javax.swing.JPanel spacing2;
    // End of variables declaration//GEN-END:variables
}
