/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import view.customClasses.RoundedButton;
import view.customClasses.PlaceholderFields;
import controller.RegistrationController;
import java.awt.*;
import javax.swing.*;
import javax.swing.JTextField;

/**
 *
 * @author Pedro Schneider, Gabriel Santana Dias
 */
public class RegistrationWindow extends javax.swing.JFrame {

    Toolkit toolkit = Toolkit.getDefaultToolkit();
    private  Dimension screenSize = toolkit.getScreenSize();
    private final int width = 512;
    private final int height = 576;
    
    /**
     * Creates new form LoginWindow
     */
    public RegistrationWindow() {
        initComponents();
        c = new RegistrationController(this);
        
        this.setSize(width, height);
        
        // changes window icon
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/view/logos_imgs/logoSpotifei.png")).getImage());
        
        // get the screen size and center the window
        int x = (screenSize.width - width) / 2;
        int y = (screenSize.height - height) / 2;
        
        this.setLocation(new Point(x,y));    
        
        // center panel after layout is initialized
        SwingUtilities.invokeLater(() -> centerLoginPanel());
    }

    private void centerLoginPanel() {
        int panelHeight = register_pnl_all.getHeight();
        int loginPanelHeight = register_pnl_registration.getPreferredSize().height;
        int logoHeight = register_pnl_titleLogo.getPreferredSize().height;

        int topMargin = 20;
        int spaceAfterLogo = 30;

        int remainingHeight = panelHeight - (logoHeight + topMargin + spaceAfterLogo);
        int y = logoHeight + topMargin + spaceAfterLogo + (remainingHeight - loginPanelHeight) / 2;

        int panelWidth = register_pnl_all.getWidth();
        int loginPanelWidth = register_pnl_registration.getPreferredSize().width;
        int x = (panelWidth - loginPanelWidth) / 2;

        // important: set layout to null for manual placement
        register_pnl_all.setLayout(null);
        register_pnl_titleLogo.setBounds((panelWidth - register_pnl_titleLogo.getPreferredSize().width) / 2, topMargin,
                                      register_pnl_titleLogo.getPreferredSize().width,
                                      register_pnl_titleLogo.getPreferredSize().height);

        register_pnl_registration.setBounds(x, y - 20, loginPanelWidth, loginPanelHeight);

        register_pnl_all.revalidate();
        register_pnl_all.repaint();
    }

    public JComboBox<String> getCbox_gender() {
        return cbox_gender;
    }

    public void setCbox_gender(JComboBox<String> cbox_gender) {
        this.cbox_gender = cbox_gender;
    }

    public JLabel getLbl_title() {
        return lbl_title;
    }

    public void setLbl_title(JLabel lbl_title) {
        this.lbl_title = lbl_title;
    }

    public JFormattedTextField getTxt_birthDate() {
        return txt_birthDate;
    }

    public void setTxt_birthDate(JFormattedTextField txt_birthDate) {
        this.txt_birthDate = txt_birthDate;
    }
    
    public JTextField getTxt_login() {
        return txt_login;
    }

    public void setTxt_login(JTextField txt_login) {
        this.txt_login = txt_login;
    }

    public JTextField getTxt_name() {
        return txt_name;
    }

    public void setTxt_name(JTextField txt_name) {
        this.txt_name = txt_name;
    }

    public JTextField getTxt_password() {
        return txt_password;
    }

    public void setTxt_password(JTextField txt_password) {
        this.txt_password = txt_password;
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        register_pnl_all = new javax.swing.JPanel();
        register_pnl_titleLogo = new javax.swing.JPanel();
        icon_logo = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        register_pnl_registration = new javax.swing.JPanel();
        txt_name = new PlaceholderFields("Digite seu nome...", new Insets(0, 15, 0, 0));
        javax.swing.text.MaskFormatter dateFormatter = null;
        try {
            dateFormatter = new javax.swing.text.MaskFormatter("##/##/####");
            dateFormatter.setPlaceholderCharacter('_');
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_birthDate = new PlaceholderFields(dateFormatter, "01/01/2000", new Insets(0, 15, 0, 0));
        txt_login = new PlaceholderFields("Digite seu login...", new Insets(0, 15, 0, 0));
        txt_password = new PlaceholderFields("Digite sua senha...", new Insets(0, 15, 0, 0));
        cbox_gender = new javax.swing.JComboBox<>();
        register_btt_pnl = new javax.swing.JPanel();
        btt_cadastrar = new RoundedButton("Cadastrar") ;
        btt_return = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spotifei");
        setBackground(new java.awt.Color(28, 28, 28));
        setResizable(false);

        register_pnl_all.setBackground(new java.awt.Color(28, 28, 28));

        register_pnl_titleLogo.setBackground(new java.awt.Color(28, 28, 28));

        icon_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logos_imgs/logoSpotifei.png"))); // NOI18N
        icon_logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbl_title.setFont(new Font("Gotham Black", Font.PLAIN, 24));
        lbl_title.setForeground(new java.awt.Color(30, 215, 96));
        lbl_title.setText("Spotifei");

        javax.swing.GroupLayout register_pnl_titleLogoLayout = new javax.swing.GroupLayout(register_pnl_titleLogo);
        register_pnl_titleLogo.setLayout(register_pnl_titleLogoLayout);
        register_pnl_titleLogoLayout.setHorizontalGroup(
            register_pnl_titleLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(register_pnl_titleLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_title)
                .addContainerGap())
        );
        register_pnl_titleLogoLayout.setVerticalGroup(
            register_pnl_titleLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(register_pnl_titleLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(register_pnl_titleLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon_logo)
                    .addGroup(register_pnl_titleLogoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbl_title)))
                .addContainerGap())
        );

        register_pnl_registration.setBackground(new java.awt.Color(28, 28, 28));

        txt_name.setBackground(new java.awt.Color(51, 51, 51));
        txt_name.setFont(new java.awt.Font("Gotham Thin", 1, 14));
        txt_name.setForeground(new java.awt.Color(168, 170, 170));
        txt_name.setBorder(null);
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        txt_birthDate.setBackground(new java.awt.Color(51, 51, 51));
        txt_birthDate.setBorder(null);
        txt_birthDate.setForeground(new java.awt.Color(168, 168, 168));
        txt_birthDate.setFont(new java.awt.Font("Gotham Thin", 1, 14));

        txt_login.setBackground(new java.awt.Color(51, 51, 51));
        txt_login.setFont(new java.awt.Font("Gotham Thin", 1, 14));
        txt_login.setForeground(new java.awt.Color(168, 170, 170));
        txt_login.setBorder(null);
        txt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_loginActionPerformed(evt);
            }
        });

        txt_password.setBackground(new java.awt.Color(51, 51, 51));
        txt_password.setFont(new java.awt.Font("Gotham Thin", 1, 14));
        txt_password.setForeground(new java.awt.Color(168, 170, 170));
        txt_password.setBorder(null);
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });

        cbox_gender.setBackground(new java.awt.Color(51, 51, 51));
        cbox_gender.setFont(new java.awt.Font("Gotham Thin", 1, 14));
        cbox_gender.setForeground(new java.awt.Color(168, 170, 170));
        cbox_gender.setMaximumRowCount(3);
        cbox_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outro" }));
        cbox_gender.setToolTipText("");
        cbox_gender.setBorder(null);
        cbox_gender.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        register_btt_pnl.setBackground(new java.awt.Color(28, 28, 28));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        register_btt_pnl.setLayout(flowLayout1);

        btt_cadastrar.setBackground(new java.awt.Color(185, 192, 198));
        btt_cadastrar.setFont(new java.awt.Font("Gotham Black", Font.PLAIN, 18));
        btt_cadastrar.setForeground(new java.awt.Color(28, 28, 28));
        btt_cadastrar.setText("Cadastrar");
        btt_cadastrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 28, 28), 1, true));
        btt_cadastrar.setBorderPainted(false);
        btt_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btt_cadastrar.setPreferredSize(new java.awt.Dimension(170, 50));
        btt_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_cadastrarActionPerformed(evt);
            }
        });
        register_btt_pnl.add(btt_cadastrar);

        javax.swing.GroupLayout register_pnl_registrationLayout = new javax.swing.GroupLayout(register_pnl_registration);
        register_pnl_registration.setLayout(register_pnl_registrationLayout);
        register_pnl_registrationLayout.setHorizontalGroup(
            register_pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(register_btt_pnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, register_pnl_registrationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(register_pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_birthDate)
                    .addComponent(txt_login, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addComponent(txt_password, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addComponent(txt_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addComponent(cbox_gender, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        register_pnl_registrationLayout.setVerticalGroup(
            register_pnl_registrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, register_pnl_registrationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_birthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbox_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(register_btt_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        btt_return.setBackground(new java.awt.Color(28, 28, 28));
        btt_return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logos_imgs/returnArrow.png"))); // NOI18N
        btt_return.setBorder(null);
        btt_return.setBorderPainted(false);
        btt_return.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btt_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_returnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout register_pnl_allLayout = new javax.swing.GroupLayout(register_pnl_all);
        register_pnl_all.setLayout(register_pnl_allLayout);
        register_pnl_allLayout.setHorizontalGroup(
            register_pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, register_pnl_allLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(register_pnl_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(register_pnl_allLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btt_return)
                .addGap(135, 135, 135)
                .addComponent(register_pnl_titleLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        register_pnl_allLayout.setVerticalGroup(
            register_pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(register_pnl_allLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(register_pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(register_pnl_titleLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btt_return))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(register_pnl_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(register_pnl_all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(register_pnl_all, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void btt_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_cadastrarActionPerformed
        // TODO add your handling code here:        
        c.saveUser();
    }//GEN-LAST:event_btt_cadastrarActionPerformed

    private void txt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_loginActionPerformed

    private void btt_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_returnActionPerformed
        // TODO add your handling code here:
        LoginWindow lw = new LoginWindow();        
        lw.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btt_returnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginWindow().setVisible(true);
//            }
//        });
//    }

    private RegistrationController c;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_cadastrar;
    private javax.swing.JButton btt_return;
    private javax.swing.JComboBox<String> cbox_gender;
    private javax.swing.JLabel icon_logo;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JPanel register_btt_pnl;
    private javax.swing.JPanel register_pnl_all;
    private javax.swing.JPanel register_pnl_registration;
    private javax.swing.JPanel register_pnl_titleLogo;
    private javax.swing.JFormattedTextField txt_birthDate;
    private javax.swing.JTextField txt_login;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_password;
    // End of variables declaration//GEN-END:variables
}
