/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.customClasses.RoundedButton;
import java.awt.*;
import model.User;
import view.customClasses.*;
import view.customClasses.RoundedButton.TextAlign;

/**
 *
 * @author Pedro Schneider, Gabriel Santana Dias
 */
public class SearchWindow extends javax.swing.JFrame {
    
    Toolkit toolkit = Toolkit.getDefaultToolkit();
    private final Dimension screenSize = toolkit.getScreenSize();
    private final int width = screenSize.width;
    private final int height = screenSize.height;
    private User user;
    
    /**
     * Creates new form HomeWindow
     */
    public SearchWindow(User user) {
        initComponents();
        this.user = user;

        this.setSize(width, height);
        
        // changes window icon
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/view/logos_imgs/logoSpotifei.png")).getImage());
        
        // center the window

        int x = (screenSize.width - width) / 2;
        int y = (screenSize.height - height) / 2;
        
        this.setLocation(new Point(x,y));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home_pnl_all = new javax.swing.JPanel();
        search_pnl_leftSide = new javax.swing.JPanel();
        home_pnl_titleLogo = new javax.swing.JPanel();
        icon_logo = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        home_pnl_options = new javax.swing.JPanel();
        home_pnl_homeOpt = new javax.swing.JPanel();
        icon_home = new javax.swing.JLabel();
        lbl_home = new javax.swing.JLabel();
        home_pnl_searchOpt = new javax.swing.JPanel();
        icon_search = new javax.swing.JLabel();
        lbl_search = new javax.swing.JLabel();
        home_pnl_playlistOpt = new javax.swing.JPanel();
        icon_playlist = new javax.swing.JLabel();
        lbl_playlist = new javax.swing.JLabel();
        search_pnl_topSide = new javax.swing.JPanel();
        search_pnl_botSide = new javax.swing.JPanel();
        search_pnl_inside = new javax.swing.JPanel();
        search_pnl_bar = new RoundedPanel();
        search_name = new PlaceholderFields("Digite o nome da música...", new Insets(0, 15, 0, 0));
        icon1 = new javax.swing.JLabel();
        btt_profile = new RoundedButton("user_name");
        search_pnl_musics = new javax.swing.JPanel();
        scroll_pane = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spotifei");
        setResizable(false);

        home_pnl_all.setBackground(new java.awt.Color(28, 28, 28));

        search_pnl_leftSide.setBackground(new java.awt.Color(28, 28, 28));

        home_pnl_titleLogo.setBackground(new java.awt.Color(28, 28, 28));

        icon_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logos_imgs/logoSpotifei.png"))); // NOI18N
        icon_logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbl_title.setFont(new java.awt.Font("Fira Mono Medium", 0, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(30, 215, 96));
        lbl_title.setText("Spotifei");

        javax.swing.GroupLayout home_pnl_titleLogoLayout = new javax.swing.GroupLayout(home_pnl_titleLogo);
        home_pnl_titleLogo.setLayout(home_pnl_titleLogoLayout);
        home_pnl_titleLogoLayout.setHorizontalGroup(
            home_pnl_titleLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_pnl_titleLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_title)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        home_pnl_titleLogoLayout.setVerticalGroup(
            home_pnl_titleLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_pnl_titleLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(home_pnl_titleLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon_logo)
                    .addGroup(home_pnl_titleLogoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbl_title)))
                .addContainerGap())
        );

        home_pnl_options.setBackground(new java.awt.Color(28, 28, 28));
        home_pnl_options.setPreferredSize(new java.awt.Dimension(0, 348));
        home_pnl_options.setLayout(new javax.swing.BoxLayout(home_pnl_options, javax.swing.BoxLayout.Y_AXIS));

        home_pnl_homeOpt.setBackground(new java.awt.Color(28, 28, 28));
        home_pnl_homeOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_pnl_homeOpt.setPreferredSize(new java.awt.Dimension(65, 58));
        home_pnl_homeOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_pnl_homeOptMouseClicked(evt);
            }
        });

        icon_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logos_imgs/homeIcon.png"))); // NOI18N
        home_pnl_homeOpt.add(icon_home);

        lbl_home.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lbl_home.setForeground(new java.awt.Color(168, 170, 170));
        lbl_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_home.setText("Home");
        home_pnl_homeOpt.add(lbl_home);

        home_pnl_options.add(home_pnl_homeOpt);

        home_pnl_searchOpt.setBackground(new java.awt.Color(28, 28, 28));
        home_pnl_searchOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_pnl_searchOpt.setPreferredSize(new java.awt.Dimension(65, 58));
        home_pnl_searchOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_pnl_searchOptMouseClicked(evt);
            }
        });

        icon_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logos_imgs/searchIcon.png"))); // NOI18N
        home_pnl_searchOpt.add(icon_search);

        lbl_search.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lbl_search.setForeground(new java.awt.Color(168, 170, 170));
        lbl_search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_search.setText("Buscar");
        home_pnl_searchOpt.add(lbl_search);

        home_pnl_options.add(home_pnl_searchOpt);

        home_pnl_playlistOpt.setBackground(new java.awt.Color(28, 28, 28));
        home_pnl_playlistOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_pnl_playlistOpt.setPreferredSize(new java.awt.Dimension(65, 58));
        home_pnl_playlistOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_pnl_playlistOptMouseClicked(evt);
            }
        });

        icon_playlist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logos_imgs/playlistIcon.png"))); // NOI18N
        home_pnl_playlistOpt.add(icon_playlist);

        lbl_playlist.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lbl_playlist.setForeground(new java.awt.Color(168, 170, 170));
        lbl_playlist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_playlist.setText("Playlists");
        home_pnl_playlistOpt.add(lbl_playlist);

        home_pnl_options.add(home_pnl_playlistOpt);

        javax.swing.GroupLayout search_pnl_leftSideLayout = new javax.swing.GroupLayout(search_pnl_leftSide);
        search_pnl_leftSide.setLayout(search_pnl_leftSideLayout);
        search_pnl_leftSideLayout.setHorizontalGroup(
            search_pnl_leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_pnl_leftSideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(search_pnl_leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home_pnl_options, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(home_pnl_titleLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        search_pnl_leftSideLayout.setVerticalGroup(
            search_pnl_leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_pnl_leftSideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(home_pnl_titleLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(home_pnl_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(440, Short.MAX_VALUE))
        );

        search_pnl_topSide.setBackground(new java.awt.Color(28, 28, 28));

        javax.swing.GroupLayout search_pnl_topSideLayout = new javax.swing.GroupLayout(search_pnl_topSide);
        search_pnl_topSide.setLayout(search_pnl_topSideLayout);
        search_pnl_topSideLayout.setHorizontalGroup(
            search_pnl_topSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        search_pnl_topSideLayout.setVerticalGroup(
            search_pnl_topSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        search_pnl_botSide.setBackground(new java.awt.Color(28, 28, 28));

        javax.swing.GroupLayout search_pnl_botSideLayout = new javax.swing.GroupLayout(search_pnl_botSide);
        search_pnl_botSide.setLayout(search_pnl_botSideLayout);
        search_pnl_botSideLayout.setHorizontalGroup(
            search_pnl_botSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        search_pnl_botSideLayout.setVerticalGroup(
            search_pnl_botSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        search_pnl_inside.setBackground(new java.awt.Color(18, 18, 18));
        search_pnl_inside.setPreferredSize(new java.awt.Dimension(48, 20));

        search_pnl_bar.setPreferredSize(new java.awt.Dimension(289, 0));

        ((PlaceholderFields) search_name).setBackgroundColor(new Color(185,192,198));
        ((PlaceholderFields) search_name).setInputColor(new Color(28,28,28));
        ((PlaceholderFields) search_name).setPlaceholderColor(new Color(28,28,28));
        ((PlaceholderFields) search_name).setHoverBackgroundColor(new Color(185,192,198));
        search_name.setBackground(new java.awt.Color(185, 192, 198));
        search_name.setFont(new java.awt.Font("Fira Mono", 1, 14)); // NOI18N
        search_name.setForeground(new java.awt.Color(168, 170, 170));
        search_name.setBorder(null);
        search_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_nameActionPerformed(evt);
            }
        });

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logos_imgs/searchIcon_gray_small.png"))); // NOI18N

        javax.swing.GroupLayout search_pnl_barLayout = new javax.swing.GroupLayout(search_pnl_bar);
        search_pnl_bar.setLayout(search_pnl_barLayout);
        search_pnl_barLayout.setHorizontalGroup(
            search_pnl_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_pnl_barLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search_name, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon1)
                .addContainerGap())
        );
        search_pnl_barLayout.setVerticalGroup(
            search_pnl_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_pnl_barLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search_name, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(icon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ((RoundedPanel) search_pnl_bar).setCornerRadiusHorizontal(80);
        ((RoundedPanel) search_pnl_bar).setCornerRadiusHorizontal(40);
        ((RoundedPanel) search_pnl_bar).setNormalColor(new Color(185,192,198));
        ((RoundedPanel) search_pnl_bar).setHoverColor(new Color(185,192,198));

        ((RoundedButton) btt_profile).setTextAlignment(TextAlign.LEFT);
        btt_profile.setBackground(new java.awt.Color(185, 192, 198));
        btt_profile.setFont(new java.awt.Font("Fira Mono", 1, 12)); // NOI18N
        btt_profile.setForeground(new java.awt.Color(28, 28, 28));
        btt_profile.setText("user_name");
        btt_profile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 28, 28), 1, true));
        btt_profile.setBorderPainted(false);
        btt_profile.setPreferredSize(new Dimension(200,30));
        btt_profile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ((RoundedButton) btt_profile).setCornerRadiusVertical(80);
        ((RoundedButton) btt_profile).setCornerRadiusHorizontal(40);
        btt_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_profileActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scroll_pane.setViewportView(jList1);

        javax.swing.GroupLayout search_pnl_musicsLayout = new javax.swing.GroupLayout(search_pnl_musics);
        search_pnl_musics.setLayout(search_pnl_musicsLayout);
        search_pnl_musicsLayout.setHorizontalGroup(
            search_pnl_musicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_pnl_musicsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll_pane)
                .addContainerGap())
        );
        search_pnl_musicsLayout.setVerticalGroup(
            search_pnl_musicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_pnl_musicsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll_pane, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout search_pnl_insideLayout = new javax.swing.GroupLayout(search_pnl_inside);
        search_pnl_inside.setLayout(search_pnl_insideLayout);
        search_pnl_insideLayout.setHorizontalGroup(
            search_pnl_insideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_pnl_insideLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(search_pnl_insideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search_pnl_musics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(search_pnl_insideLayout.createSequentialGroup()
                        .addComponent(search_pnl_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                        .addComponent(btt_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        search_pnl_insideLayout.setVerticalGroup(
            search_pnl_insideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_pnl_insideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(search_pnl_insideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btt_profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_pnl_bar, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(search_pnl_musics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout home_pnl_allLayout = new javax.swing.GroupLayout(home_pnl_all);
        home_pnl_all.setLayout(home_pnl_allLayout);
        home_pnl_allLayout.setHorizontalGroup(
            home_pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(search_pnl_botSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(home_pnl_allLayout.createSequentialGroup()
                .addComponent(search_pnl_leftSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(home_pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search_pnl_inside, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                    .addComponent(search_pnl_topSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        home_pnl_allLayout.setVerticalGroup(
            home_pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_pnl_allLayout.createSequentialGroup()
                .addGroup(home_pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(home_pnl_allLayout.createSequentialGroup()
                        .addComponent(search_pnl_topSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search_pnl_inside, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE))
                    .addComponent(search_pnl_leftSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_pnl_botSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_pnl_all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_pnl_all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_pnl_homeOptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_pnl_homeOptMouseClicked
        // TODO add your handling code here:
        HomeWindow hw = new HomeWindow(user);
        hw.setVisible(rootPaneCheckingEnabled);
        this.setVisible(false);
    }//GEN-LAST:event_home_pnl_homeOptMouseClicked

    private void home_pnl_searchOptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_pnl_searchOptMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_home_pnl_searchOptMouseClicked

    private void home_pnl_playlistOptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_pnl_playlistOptMouseClicked
        // TODO add your handling code here:
        PlaylistsWindow pw = new PlaylistsWindow(user);
        pw.setVisible(rootPaneCheckingEnabled);
        this.setVisible(false);
    }//GEN-LAST:event_home_pnl_playlistOptMouseClicked

    private void btt_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_profileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btt_profileActionPerformed

    private void search_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_nameActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomeWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_profile;
    private javax.swing.JPanel home_pnl_all;
    private javax.swing.JPanel home_pnl_homeOpt;
    private javax.swing.JPanel home_pnl_options;
    private javax.swing.JPanel home_pnl_playlistOpt;
    private javax.swing.JPanel home_pnl_searchOpt;
    private javax.swing.JPanel home_pnl_titleLogo;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon_home;
    private javax.swing.JLabel icon_logo;
    private javax.swing.JLabel icon_playlist;
    private javax.swing.JLabel icon_search;
    private javax.swing.JList<String> jList1;
    private javax.swing.JLabel lbl_home;
    private javax.swing.JLabel lbl_playlist;
    private javax.swing.JLabel lbl_search;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JScrollPane scroll_pane;
    private javax.swing.JTextField search_name;
    private javax.swing.JPanel search_pnl_bar;
    private javax.swing.JPanel search_pnl_botSide;
    private javax.swing.JPanel search_pnl_inside;
    private javax.swing.JPanel search_pnl_leftSide;
    private javax.swing.JPanel search_pnl_musics;
    private javax.swing.JPanel search_pnl_topSide;
    // End of variables declaration//GEN-END:variables
}
