/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.MusicSearchController;
import view.customClasses.RoundedButton;
import java.awt.*;
import javax.swing.*;
import model.User;
import view.customClasses.*;
import view.customClasses.RoundedButton.TextAlign;

/**
 *
 * @author Pedro Schneider, Gabriel Santana Dias
 */
public class SearchWindow extends javax.swing.JFrame {
    
    Toolkit toolkit = Toolkit.getDefaultToolkit();
    private final Dimension screenSize = toolkit.getScreenSize();
    private final int width = screenSize.width;
    private final int height = screenSize.height;
    private User user;
    
    /**
     * Creates new form HomeWindow
     */
    public SearchWindow(User user) {
        initComponents();
        c = new MusicSearchController(this, user);
        this.user = user;

        this.setSize(width, height);
        
        // changes window icon
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/view/logos_imgs/logoSpotifei.png")).getImage());
        
        // center the window
        int x = (screenSize.width - width) / 2;
        int y = (screenSize.height - height) / 2;
        
        this.setLocation(new Point(x,y));
        
        SwingUtilities.invokeLater(() -> {
            list_musics.requestFocusInWindow();
        });
        c.setUserNameOnWindow();
    }

    public JTextField getSearch_name() {
        return search_name;
    }

    public void setSearch_name(JTextField search_name) {
        this.search_name = search_name;
    }

    public JList<String> getjList1() {
        return list_musics;
    }

    public void setjList1(JList<String> jList1) {
        this.list_musics = jList1;
    }

    public JLabel getLbl_musicArtist() {
        return lbl_musicArtist;
    }

    public void setLbl_musicArtist(JLabel lbl_musicArtist) {
        this.lbl_musicArtist = lbl_musicArtist;
    }

    public JLabel getLbl_musicDescription() {
        return lbl_musicDescription;
    }

    public void setLbl_musicDescription(JLabel lbl_musicDescription) {
        this.lbl_musicDescription = lbl_musicDescription;
    }

    public JLabel getLbl_musicDislikes() {
        return lbl_musicDislikes;
    }

    public void setLbl_musicDislikes(JLabel lbl_musicDislikes) {
        this.lbl_musicDislikes = lbl_musicDislikes;
    }

    public JLabel getLbl_musicDuration() {
        return lbl_musicDuration;
    }

    public void setLbl_musicDuration(JLabel lbl_musicDuration) {
        this.lbl_musicDuration = lbl_musicDuration;
    }

    public JLabel getLbl_musicGenre() {
        return lbl_musicGenre;
    }

    public void setLbl_musicGenre(JLabel lbl_musicGenre) {
        this.lbl_musicGenre = lbl_musicGenre;
    }

    public JLabel getLbl_musicLikes() {
        return lbl_musicLikes;
    }

    public void setLbl_musicLikes(JLabel lbl_musicLikes) {
        this.lbl_musicLikes = lbl_musicLikes;
    }

    public JLabel getLbl_musicTitle() {
        return lbl_musicTitle;
    }

    public void setLbl_musicTitle(JLabel lbl_musicTitle) {
        this.lbl_musicTitle = lbl_musicTitle;
    }

    public JButton getBtt_profile() {
        return btt_profile;
    }

    public void setBtt_profile(JButton btt_profile) {
        this.btt_profile = btt_profile;
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        home_pnl_all = new javax.swing.JPanel();
        search_pnl_leftSide = new javax.swing.JPanel();
        home_pnl_titleLogo = new javax.swing.JPanel();
        icon_logo = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        home_pnl_options = new javax.swing.JPanel();
        home_pnl_homeOpt = new javax.swing.JPanel();
        icon_home = new javax.swing.JLabel();
        lbl_home = new javax.swing.JLabel();
        home_pnl_searchOpt = new javax.swing.JPanel();
        icon_search = new javax.swing.JLabel();
        lbl_search = new javax.swing.JLabel();
        home_pnl_playlistOpt = new javax.swing.JPanel();
        icon_playlist = new javax.swing.JLabel();
        lbl_playlist = new javax.swing.JLabel();
        search_pnl_topSide = new javax.swing.JPanel();
        search_pnl_botSide = new javax.swing.JPanel();
        search_pnl_musicInfo = new javax.swing.JPanel();
        lbl_musicTitle = new javax.swing.JLabel();
        lbl_musicDescription = new javax.swing.JLabel();
        lbl_musicDuration = new javax.swing.JLabel();
        lbl_musicLikes = new javax.swing.JLabel();
        lbl_musicDislikes = new javax.swing.JLabel();
        lbl_musicGenre = new javax.swing.JLabel();
        lbl_musicArtist = new javax.swing.JLabel();
        search_pnl_inside = new javax.swing.JPanel();
        search_pnl_bar = new RoundedPanel();
        search_name = new PlaceholderFields("Digite o nome da música...", new Insets(0, 15, 0, 0));
        icon1 = new javax.swing.JLabel();
        btt_profile = new RoundedButton("user_name");
        search_pnl_musics = new javax.swing.JPanel();
        scroll_musics = new javax.swing.JScrollPane();
        list_musics = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spotifei");
        setResizable(false);

        home_pnl_all.setBackground(new java.awt.Color(28, 28, 28));

        search_pnl_leftSide.setBackground(new java.awt.Color(28, 28, 28));

        home_pnl_titleLogo.setBackground(new java.awt.Color(28, 28, 28));

        icon_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logos_imgs/logoSpotifei.png"))); // NOI18N
        icon_logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbl_title.setFont(new Font("Gotham Black", Font.PLAIN, 24));
        lbl_title.setForeground(new java.awt.Color(30, 215, 96));
        lbl_title.setText("Spotifei");

        javax.swing.GroupLayout home_pnl_titleLogoLayout = new javax.swing.GroupLayout(home_pnl_titleLogo);
        home_pnl_titleLogo.setLayout(home_pnl_titleLogoLayout);
        home_pnl_titleLogoLayout.setHorizontalGroup(
            home_pnl_titleLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_pnl_titleLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_title)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        home_pnl_titleLogoLayout.setVerticalGroup(
            home_pnl_titleLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_pnl_titleLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(home_pnl_titleLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon_logo)
                    .addGroup(home_pnl_titleLogoLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lbl_title)))
                .addContainerGap())
        );

        home_pnl_options.setBackground(new java.awt.Color(28, 28, 28));
        home_pnl_options.setPreferredSize(new java.awt.Dimension(0, 348));
        home_pnl_options.setLayout(new javax.swing.BoxLayout(home_pnl_options, javax.swing.BoxLayout.Y_AXIS));

        home_pnl_homeOpt.setBackground(new java.awt.Color(28, 28, 28));
        home_pnl_homeOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        home_pnl_homeOpt.setPreferredSize(new java.awt.Dimension(65, 58));
        home_pnl_homeOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_pnl_homeOptMouseClicked(evt);
            }
        });

        icon_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logos_imgs/homeIcon.png"))); // NOI18N
        home_pnl_homeOpt.add(icon_home);

        lbl_home.setFont(new Font("Gotham Black", Font.PLAIN, 16));
        lbl_home.setForeground(new java.awt.Color(168, 170, 170));
        lbl_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_home.setText("Home");
        home_pnl_homeOpt.add(lbl_home);

        home_pnl_options.add(home_pnl_homeOpt);

        home_pnl_searchOpt.setBackground(new java.awt.Color(28, 28, 28));
        home_pnl_searchOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        home_pnl_searchOpt.setPreferredSize(new java.awt.Dimension(65, 58));
        home_pnl_searchOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_pnl_searchOptMouseClicked(evt);
            }
        });

        icon_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logos_imgs/searchIcon.png"))); // NOI18N
        home_pnl_searchOpt.add(icon_search);

        lbl_search.setFont(new Font("Gotham Black", Font.PLAIN, 16));
        lbl_search.setForeground(new java.awt.Color(168, 170, 170));
        lbl_search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_search.setText("Buscar");
        home_pnl_searchOpt.add(lbl_search);

        home_pnl_options.add(home_pnl_searchOpt);

        home_pnl_playlistOpt.setBackground(new java.awt.Color(28, 28, 28));
        home_pnl_playlistOpt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        home_pnl_playlistOpt.setPreferredSize(new java.awt.Dimension(65, 58));
        home_pnl_playlistOpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_pnl_playlistOptMouseClicked(evt);
            }
        });

        icon_playlist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logos_imgs/playlistIcon.png"))); // NOI18N
        home_pnl_playlistOpt.add(icon_playlist);

        lbl_playlist.setFont(new Font("Gotham Black", Font.PLAIN, 16));
        lbl_playlist.setForeground(new java.awt.Color(168, 170, 170));
        lbl_playlist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_playlist.setText("Playlists");
        home_pnl_playlistOpt.add(lbl_playlist);

        home_pnl_options.add(home_pnl_playlistOpt);

        javax.swing.GroupLayout search_pnl_leftSideLayout = new javax.swing.GroupLayout(search_pnl_leftSide);
        search_pnl_leftSide.setLayout(search_pnl_leftSideLayout);
        search_pnl_leftSideLayout.setHorizontalGroup(
            search_pnl_leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_pnl_leftSideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(search_pnl_leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home_pnl_options, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(home_pnl_titleLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        search_pnl_leftSideLayout.setVerticalGroup(
            search_pnl_leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_pnl_leftSideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(home_pnl_titleLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(home_pnl_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(428, Short.MAX_VALUE))
        );

        search_pnl_topSide.setBackground(new java.awt.Color(28, 28, 28));

        javax.swing.GroupLayout search_pnl_topSideLayout = new javax.swing.GroupLayout(search_pnl_topSide);
        search_pnl_topSide.setLayout(search_pnl_topSideLayout);
        search_pnl_topSideLayout.setHorizontalGroup(
            search_pnl_topSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        search_pnl_topSideLayout.setVerticalGroup(
            search_pnl_topSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        search_pnl_botSide.setBackground(new java.awt.Color(28, 28, 28));

        search_pnl_musicInfo.setBackground(new java.awt.Color(28, 28, 28));
        search_pnl_musicInfo.setLayout(new java.awt.GridBagLayout());

        lbl_musicTitle.setForeground(new java.awt.Color(168, 168, 168));
        lbl_musicTitle.setText("title");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 89, 0);
        search_pnl_musicInfo.add(lbl_musicTitle, gridBagConstraints);

        lbl_musicDescription.setForeground(new java.awt.Color(168, 168, 168));
        lbl_musicDescription.setText("description");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 89, 0);
        search_pnl_musicInfo.add(lbl_musicDescription, gridBagConstraints);

        lbl_musicDuration.setForeground(new java.awt.Color(168, 168, 168));
        lbl_musicDuration.setText("duration");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 89, 0);
        search_pnl_musicInfo.add(lbl_musicDuration, gridBagConstraints);

        lbl_musicLikes.setForeground(new java.awt.Color(168, 168, 168));
        lbl_musicLikes.setText("likes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 89, 0);
        search_pnl_musicInfo.add(lbl_musicLikes, gridBagConstraints);

        lbl_musicDislikes.setForeground(new java.awt.Color(168, 168, 168));
        lbl_musicDislikes.setText("dislikes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 89, 0);
        search_pnl_musicInfo.add(lbl_musicDislikes, gridBagConstraints);

        lbl_musicGenre.setForeground(new java.awt.Color(168, 168, 168));
        lbl_musicGenre.setText("genre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 89, 0);
        search_pnl_musicInfo.add(lbl_musicGenre, gridBagConstraints);

        lbl_musicArtist.setForeground(new java.awt.Color(168, 168, 168));
        lbl_musicArtist.setText("artist");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 89, 637);
        search_pnl_musicInfo.add(lbl_musicArtist, gridBagConstraints);

        javax.swing.GroupLayout search_pnl_botSideLayout = new javax.swing.GroupLayout(search_pnl_botSide);
        search_pnl_botSide.setLayout(search_pnl_botSideLayout);
        search_pnl_botSideLayout.setHorizontalGroup(
            search_pnl_botSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_pnl_botSideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search_pnl_musicInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        search_pnl_botSideLayout.setVerticalGroup(
            search_pnl_botSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_pnl_botSideLayout.createSequentialGroup()
                .addComponent(search_pnl_musicInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        search_pnl_inside.setBackground(new java.awt.Color(18, 18, 18));
        search_pnl_inside.setPreferredSize(new java.awt.Dimension(48, 20));

        search_pnl_bar.setBackground(new java.awt.Color(51, 51, 51));
        search_pnl_bar.setPreferredSize(new java.awt.Dimension(289, 0));

        ((PlaceholderFields) search_name).setHoverBackgroundColor(new Color(51,51,51));
        search_name.setBackground(new java.awt.Color(51, 51, 51));
        search_name.setFont(new Font("Gotham Black", Font.PLAIN, 14));
        search_name.setForeground(new java.awt.Color(168, 168, 168));
        search_name.setBorder(null);
        search_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_nameActionPerformed(evt);
            }
        });

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logos_imgs/searchIcon_gray_small.png"))); // NOI18N

        javax.swing.GroupLayout search_pnl_barLayout = new javax.swing.GroupLayout(search_pnl_bar);
        search_pnl_bar.setLayout(search_pnl_barLayout);
        search_pnl_barLayout.setHorizontalGroup(
            search_pnl_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_pnl_barLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search_name, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icon1)
                .addContainerGap())
        );
        search_pnl_barLayout.setVerticalGroup(
            search_pnl_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_pnl_barLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search_name, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(icon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        ((RoundedPanel) search_pnl_bar).setCornerRadiusHorizontal(80);
        ((RoundedPanel) search_pnl_bar).setCornerRadiusHorizontal(40);
        // mesma cor de bg e hover para "desativar" a animação
        ((RoundedPanel) search_pnl_bar).setNormalColor(new Color(51,51,51));
        ((RoundedPanel) search_pnl_bar).setHoverColor(new Color(51,51,51));

        ((RoundedButton) btt_profile).setTextAlignment(TextAlign.LEFT);
        btt_profile.setBackground(new java.awt.Color(185, 192, 198));
        btt_profile.setFont(new java.awt.Font("Gotham Black", Font.PLAIN, 12));
        btt_profile.setForeground(new java.awt.Color(28, 28, 28));
        btt_profile.setText("user_name");
        btt_profile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 28, 28), 1, true));
        btt_profile.setBorderPainted(false);
        btt_profile.setPreferredSize(new Dimension(200,30));
        btt_profile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ((RoundedButton) btt_profile).setCornerRadiusVertical(80);
        ((RoundedButton) btt_profile).setCornerRadiusHorizontal(40);
        btt_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_profileActionPerformed(evt);
            }
        });

        search_pnl_musics.setBackground(new java.awt.Color(18, 18, 18));

        scroll_musics.setBackground(new java.awt.Color(60, 63, 65));
        scroll_musics.setForeground(new java.awt.Color(58, 58, 58));

        list_musics.setBackground(new java.awt.Color(191, 191, 191));
        list_musics.setBorder(null);
        list_musics.setFont(new Font("Gotham Light", Font.PLAIN, 14));
        list_musics.setForeground(new java.awt.Color(28, 28, 28));
        list_musics.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        list_musics.setSelectionBackground(new java.awt.Color(100, 165, 135));
        scroll_musics.setViewportView(list_musics);

        javax.swing.GroupLayout search_pnl_musicsLayout = new javax.swing.GroupLayout(search_pnl_musics);
        search_pnl_musics.setLayout(search_pnl_musicsLayout);
        search_pnl_musicsLayout.setHorizontalGroup(
            search_pnl_musicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll_musics)
        );
        search_pnl_musicsLayout.setVerticalGroup(
            search_pnl_musicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll_musics, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout search_pnl_insideLayout = new javax.swing.GroupLayout(search_pnl_inside);
        search_pnl_inside.setLayout(search_pnl_insideLayout);
        search_pnl_insideLayout.setHorizontalGroup(
            search_pnl_insideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_pnl_insideLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(search_pnl_insideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search_pnl_musics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(search_pnl_insideLayout.createSequentialGroup()
                        .addComponent(search_pnl_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btt_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        search_pnl_insideLayout.setVerticalGroup(
            search_pnl_insideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_pnl_insideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(search_pnl_insideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btt_profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_pnl_bar, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(search_pnl_musics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout home_pnl_allLayout = new javax.swing.GroupLayout(home_pnl_all);
        home_pnl_all.setLayout(home_pnl_allLayout);
        home_pnl_allLayout.setHorizontalGroup(
            home_pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(search_pnl_botSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(home_pnl_allLayout.createSequentialGroup()
                .addComponent(search_pnl_leftSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(home_pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search_pnl_inside, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
                    .addComponent(search_pnl_topSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        home_pnl_allLayout.setVerticalGroup(
            home_pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_pnl_allLayout.createSequentialGroup()
                .addGroup(home_pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(home_pnl_allLayout.createSequentialGroup()
                        .addComponent(search_pnl_topSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search_pnl_inside, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE))
                    .addComponent(search_pnl_leftSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_pnl_botSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_pnl_all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_pnl_all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_pnl_homeOptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_pnl_homeOptMouseClicked
        // TODO add your handling code here:
        HomeWindow hw = new HomeWindow(user);
        hw.setVisible(rootPaneCheckingEnabled);
        this.setVisible(false);
    }//GEN-LAST:event_home_pnl_homeOptMouseClicked

    private void home_pnl_searchOptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_pnl_searchOptMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_home_pnl_searchOptMouseClicked

    private void home_pnl_playlistOptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_pnl_playlistOptMouseClicked
        // TODO add your handling code here:
        PlaylistsWindow pw = new PlaylistsWindow(user);
        pw.setVisible(rootPaneCheckingEnabled);
        this.setVisible(false);
    }//GEN-LAST:event_home_pnl_playlistOptMouseClicked

    private void btt_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_profileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btt_profileActionPerformed

    private void search_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_nameActionPerformed
        // TODO add your handling code here:
        c.searchMusic();
    }//GEN-LAST:event_search_nameActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomeWindow().setVisible(true);
//            }
//        });
//    }
    
    private MusicSearchController c;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_profile;
    private javax.swing.JPanel home_pnl_all;
    private javax.swing.JPanel home_pnl_homeOpt;
    private javax.swing.JPanel home_pnl_options;
    private javax.swing.JPanel home_pnl_playlistOpt;
    private javax.swing.JPanel home_pnl_searchOpt;
    private javax.swing.JPanel home_pnl_titleLogo;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon_home;
    private javax.swing.JLabel icon_logo;
    private javax.swing.JLabel icon_playlist;
    private javax.swing.JLabel icon_search;
    private javax.swing.JLabel lbl_home;
    private javax.swing.JLabel lbl_musicArtist;
    private javax.swing.JLabel lbl_musicDescription;
    private javax.swing.JLabel lbl_musicDislikes;
    private javax.swing.JLabel lbl_musicDuration;
    private javax.swing.JLabel lbl_musicGenre;
    private javax.swing.JLabel lbl_musicLikes;
    private javax.swing.JLabel lbl_musicTitle;
    private javax.swing.JLabel lbl_playlist;
    private javax.swing.JLabel lbl_search;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JList<String> list_musics;
    private javax.swing.JScrollPane scroll_musics;
    private javax.swing.JTextField search_name;
    private javax.swing.JPanel search_pnl_bar;
    private javax.swing.JPanel search_pnl_botSide;
    private javax.swing.JPanel search_pnl_inside;
    private javax.swing.JPanel search_pnl_leftSide;
    private javax.swing.JPanel search_pnl_musicInfo;
    private javax.swing.JPanel search_pnl_musics;
    private javax.swing.JPanel search_pnl_topSide;
    // End of variables declaration//GEN-END:variables
}
